# Generated by Django 5.1.5 on 2025-02-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderpermission',
            options={'verbose_name': 'Folder Permission', 'verbose_name_plural': 'Folder Permissions'},
        ),
    ]
    