# Generated by Django 5.1.5 on 2025-02-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_folderpermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='subfolder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
