# Generated by Django 5.1.5 on 2025-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_folderpermission_subfolder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
