# Generated by Django 5.1.5 on 2025-02-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_folderpermission_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderpermission',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='folderpermission',
            name='subfolder_name',
        ),
    ]
